version: '3.3'

services:
  db:
    build:
      context: mysql
    container_name: desafio-mysql
    environment:
       MYSQL_DATABASE: nodedb
       MYSQL_ROOT_PASSWORD: edutuca
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql/
    networks:
      - desafio-networks

  node:
    build: 
      context: node
    
    container_name: desafio-node
    entrypoint: dockerize -wait tcp://desafio-mysql:3306 -timeout 160s docker-entrypoint.sh
    command: node index.js
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - desafio-networks
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: desafio-nginx
    ports:
      - 8080:80
    tty: true      
    volumes:
      - ./nginx:/etc/nginx/
    networks:
      - desafio-networks
    depends_on:
      - db      
      - node
      
networks:
   desafio-networks:
      driver: bridge